//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HDBANHANG = new HashSet<HDBANHANG>();
        }
    
        public string MANV { get; set; }
        public string MATKHAU { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public bool GIOITINH { get; set; }
        public bool XOA { get; set; }
        public string GHICHU { get; set; }
        public byte[] ANH { get; set; }
        public bool QUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDBANHANG> HDBANHANG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
